# Minimal Orange Pi 5 Pro config for Mainline (Edge)
BOARD_NAME="Orange Pi 5 Pro"
BOARD_VENDOR="xunlong"
BOARDFAMILY="rockchip-rk3588"
BOOT_SOC="rk3588"
IMAGE_PARTITION_TABLE="gpt"
BOOT_SCENARIO="binman" # Required for Mainline U-Boot packaging

# Kernel & Device Tree
BOOT_FDT_FILE="rockchip/rk3588s-orangepi-5-pro.dtb"
KERNEL_TARGET="edge"

# SPI Flash Support
BOOT_SUPPORT_SPI="yes"
BOOT_SPI_RKSPI_LOADER="yes"

# This hook name now matches BOARD=custom-orangepi5-pro
function post_family_config__custom_orangepi5_pro() {
    display_alert "$BOARD" "Applying Custom Mainline Overrides" "info"
    
    declare -g BOOTSOURCE="https://github.com/u-boot/u-boot.git"
    declare -g BOOTBRANCH="tag:v2026.04"
    declare -g BOOTCONFIG="orangepi-5-pro-rk3588s_defconfig"
    declare -g BOOTPATCHDIR="v2026.04"
    
    declare -g BL31_BLOB="rk35/rk3588_bl31_v1.51.elf"
    declare -g DDR_BLOB="rk35/rk3588_ddr_lp4_2112MHz_lp5_2400MHz_v1.19.bin"    

    declare -g UBOOT_TARGET_MAP="BL31=${RKBIN_DIR}/${BL31_BLOB} ROCKCHIP_TPL=${RKBIN_DIR}/${DDR_BLOB};;u-boot-rockchip.bin u-boot-rockchip-spi.bin"

    declare -g KERNELBRANCH="tag:v7.1"
    declare -g KERNEL_MAJOR_MINOR="7.1"

}

# This hook handles the wifi firmware symlinks
function post_family_tweaks__custom_orangepi5_pro() {
    display_alert "$BOARD" "Fixing WiFi firmware symlinks" "info"
    mkdir -p $SDCARD/lib/firmware/brcm/
    ln -sf brcmfmac43456-sdio.bin $SDCARD/lib/firmware/brcm/brcmfmac43456-sdio.xunlong,orangepi-5-pro.bin
    ln -sf brcmfmac43456-sdio.txt $SDCARD/lib/firmware/brcm/brcmfmac43456-sdio.xunlong,orangepi-5-pro.txt
}
